apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zcm-env-local.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
data:
  NODE_IP_ADDR: 10.45.80.82