apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zcm-timezone.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
data:
  timezone: Asia/Shanghai