apiVersion: v1
data:
  mysql-root-passwd: {{ .Values.secret.mysqlrootpasswd }}
kind: Secret
metadata:
  name: {{ include "zcm-mysql.fullname" . }}
  namespace: {{ .Values.namespace }}
type: {{ .Values.secret.type }}
