apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zcm-service.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
data:
  {{- (.Files.Glob "files/*").AsConfig | nindent 2 }}