# Default values for zcm-ansible.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: zcm-ansible

replicaCount: 1

restartPolicy: Always

image:
  repository: zcm9/zcm-ansible
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: C_20201015102305

env:
  - name: LANG
    value: en_US.UTF-8
  - name: CLOUD_APP_NAME
    value: paas_zcm-ansible
  - name: ZCM_ZCAMP_ANSIBLE_SERVER_PORT
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_ZCAMP_ANSIBLE_SERVER_PORT
  - name: ZCAMP_ANSIBLE_REST_SERVER
    value: "http://zcm-zcamp-rest-server.zcm9.svc.cluster.local:8081/rest"
  - name: ZCAMP_JEDIS_HOST
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_REDIS_SERVER_LIST
  - name: ZCAMP_JEDIS_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_REDIS_PASSWORD
  - name: ZCAMP_JDBC_URL
    value: "jdbc:mysql://zcm-mysql.zcm9.svc.cluster.local:3306/zcm_portal_9?zeroDateTimeBehavior=convertToNull\\&allowMultiQueries=true"
  - name: ZCAMP_JDBC_USR
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_MYSQL_USER
  - name: ZCAMP_JDBC_PASS
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_MYSQL_PASSWORD

resources:
  requests:
    cpu: 1
    memory: 4096Mi
  limits:
    cpu: 4
    memory: 4096Mi

ports:
  - containerPort: 52780
    protocol: TCP
    name: http
  - containerPort: 8443
    protocol: TCP
    name: https

volumeMounts:
  - name: localtime
    mountPath: /etc/localtime
    readOnly: True
  - name: zcm-timezone
    mountPath: /etc/timezone
    subPath: timezone
    readOnly: True

volumes:
  - name: localtime
    hostPath:
      path: /etc/localtime

cm:
  - name: zcm-timezone
    configMap:
      name: zcm-timezone

service:
  type: ClusterIP
  ports:
    - name: http
      port: 52780
      protocol: TCP
      targetPort: 52780
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 25780

dnsPolicy: ClusterFirst
clusterIP: None