# Default values for zcm-nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: zcm-nginx

replicaCount: 1

restartPolicy: Always

image:
  repository: zcm9/zcm-nginx-aik
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: C_20201222105649

env:
  - name: CLOUD_APP_NAME
    value: paas_zcm-nginx
  - name: ZCM_DOMAIN
    valueFrom:
      configMapKeyRef:
        name: zcm-env-base
        key: ZCM_DOMAIN

resources:
  requests:
    cpu: 0.5
    memory: 512Mi
  limits:
    cpu: 4
    memory: 4096Mi

ports:
  - containerPort: 52000
    protocol: TCP
    name: http
  - containerPort: 25000
    protocol: TCP
    name: https

volumeMounts:
  - name: config
    mountPath: /zcm/httpfiles/k8s/certs/cluster_192.168.0.3/config
    subPath: config
    readOnly: True
  - name: localtime
    mountPath: /etc/localtime
    readOnly: True
  - name: zcm-timezone
    mountPath: /etc/timezone
    subPath: timezone
    readOnly: True

volumes:
  - name: localtime
    hostPath:
      path: /etc/localtime

cm:
  - name: config
    configMap:
      name: zcm-nginx
  - name: zcm-timezone
    configMap:
      name: zcm-timezone

hostAliases:
  - ip: 172.24.128.253
    hostnames:
      - harbor.dcos.ncmp.unicom.local

service:
  type: ClusterIP
  ports:
    - name: http
      port: 52000
      protocol: TCP
      targetPort: 52000
    - name: https
      port: 25000
      protocol: TCP
      targetPort: 25000
  typeouter: NodePort
  portsouter:
    - name: http
      port: 52000
      protocol: TCP
      targetPort: 52000
      nodePort: 32000
    - name: https
      port: 25000
      protocol: TCP
      targetPort: 25000
      nodePort: 32001

dnsPolicy: ClusterFirst
clusterIP: None